FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*

COPY requirements.api.txt ./
RUN pip install -r requirements.api.txt

COPY data/06_models ./data/06_models
COPY src ./src

CMD ["uvicorn","src.api.main:app","--host","0.0.0.0","--port","8000"]