FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml ./
COPY requirements.api.txt ./
COPY src ./src
COPY data/06_models ./data/06_models
RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.api.txt
CMD ["uvicorn","src.api.main:app","--host","0.0.0.0","--port","8000"]