FROM python:3.11-slim
WORKDIR /app

COPY requirements.ui.txt ./
RUN pip install -r requirements.ui.txt

COPY src ./src

EXPOSE 8501
ENV API_URL=http://api:8000

CMD ["streamlit","run","src/ui/app.py","--server.address","0.0.0.0","--server.port","8501"]