name: asi-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - pre-commit
      - ruff
      - black
      - pytest
      - wandb
      - kedro
      - kedro-datasets-2.1.0[pandas]
      - kedro-datasets-2.1.0[pickle]
      - kedro-datasets-2.1.0[tracking]
      - pyarrow
      - pytest


  - pyyaml
