_wandb:
    value:
        cli_version: 0.22.3
        e:
            g9hb4ens0md1d9yl74dlquzwvx9fbpfc:
                args:
                    - run
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "999286632448"
                        used: "886508900352"
                email: s27335@pjwstk.edu.pl
                executable: C:\Users\bart_\anaconda3\envs\asi-ml\python.exe
                git:
                    commit: 3ebc420fc53eac49d990e5e51da6e921b5b51d0e
                    remote: https://github.com/dzian1s/ASI-ML-2025-zespol.git
                host: Bartek
                memory:
                    total: "34104049664"
                os: Windows-10-10.0.26100-SP0
                program: -m __main__
                python: CPython 3.11.14
                root: C:\Users\bart_\OneDrive\Pulpit\ASI\ASI-ML-2025-zespol
                startedAt: "2025-10-29T14:32:25.716712Z"
                writerId: g9hb4ens0md1d9yl74dlquzwvx9fbpfc
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 16
            "4": 3.11.14
            "5": 0.22.3
            "8":
                - 2
                - 3
            "10":
                - 20
            "12": 0.22.3
            "13": windows-amd64
n_estimators:
    value: 100
random_state:
    value: 42
