split:
  test_size: 0.2
  random_state: 42

model_opts:
  n_estimators: 100
  random_state: 42

autogluon:
  time_limit: 120
  presets: "best_quality"
  problem_type: "regression"
  label: "price"
  eval_metric: "rmse"
  random_seed: 50
